// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission_8_Group_7.Data;

#nullable disable

namespace Mission_8_Group_7.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20260226155745_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Mission_8_Group_7.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("Mission_8_Group_7.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskItemId = 1,
                            CategoryId = 1,
                            Completed = false,
                            DueDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 1,
                            Task = "Finish project presentation"
                        },
                        new
                        {
                            TaskItemId = 2,
                            CategoryId = 3,
                            Completed = false,
                            DueDate = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 1,
                            Task = "Study for exam tomorrow"
                        },
                        new
                        {
                            TaskItemId = 3,
                            CategoryId = 4,
                            Completed = false,
                            DueDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 2,
                            Task = "Plan weekly workout schedule"
                        },
                        new
                        {
                            TaskItemId = 4,
                            CategoryId = 2,
                            Completed = false,
                            DueDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 2,
                            Task = "Read personal development book"
                        },
                        new
                        {
                            TaskItemId = 5,
                            CategoryId = 1,
                            Completed = false,
                            DueDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 3,
                            Task = "Reply to non-critical work emails"
                        },
                        new
                        {
                            TaskItemId = 6,
                            CategoryId = 4,
                            Completed = false,
                            DueDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 3,
                            Task = "Schedule dentist appointment"
                        },
                        new
                        {
                            TaskItemId = 7,
                            CategoryId = 2,
                            Completed = false,
                            DueDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 4,
                            Task = "Reorganize old photo albums"
                        });
                });

            modelBuilder.Entity("Mission_8_Group_7.Models.TaskItem", b =>
                {
                    b.HasOne("Mission_8_Group_7.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Mission_8_Group_7.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
